// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers.Gfbmdl
{
    using global::System;
    using global::FlatBuffers;

    public enum BoneType : uint
    {
        NoSkinning = 0,
        HasSkinning = 1,
    };

    public enum VertexType : uint
    {
        Position = 0,
        Normal = 1,
        Binormal = 2,
        UV1 = 3,
        UV2 = 4,
        UV3 = 5,
        UV4 = 6,
        Color1 = 7,
        Color2 = 8,
        Color3 = 9,
        Color4 = 10,
        BoneID = 11,
        BoneWeight = 12,
    };

    public enum BufferFormat : uint
    {
        Float = 0,
        HalfFloat = 1,
        Byte = 3,
        Short = 5,
        BytesAsFloat = 8,
    };

    public struct Model : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static Model GetRootAsModel(ByteBuffer _bb) { return GetRootAsModel(_bb, new Model()); }
        public static Model GetRootAsModel(ByteBuffer _bb, Model obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Model __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public BoundingBox? Bounding { get { int o = __p.__offset(6); return o != 0 ? (BoundingBox?)(new BoundingBox()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public string TextureNames(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
        public int TextureNamesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
        public string ShaderNames(int j) { int o = __p.__offset(10); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
        public int ShaderNamesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
        public UnknownEmpty? Unknown(int j) { int o = __p.__offset(12); return o != 0 ? (UnknownEmpty?)(new UnknownEmpty()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int UnknownLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
        public string MaterialNames(int j) { int o = __p.__offset(14); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
        public int MaterialNamesLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
        public Material? Materials(int j) { int o = __p.__offset(16); return o != 0 ? (Material?)(new Material()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int MaterialsLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
        public Group? Groups(int j) { int o = __p.__offset(18); return o != 0 ? (Group?)(new Group()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int GroupsLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
        public Mesh? Meshes(int j) { int o = __p.__offset(20); return o != 0 ? (Mesh?)(new Mesh()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int MeshesLength { get { int o = __p.__offset(20); return o != 0 ? __p.__vector_len(o) : 0; } }
        public Bone? Bones(int j) { int o = __p.__offset(22); return o != 0 ? (Bone?)(new Bone()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int BonesLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
        public RenderInfo? RenderData(int j) { int o = __p.__offset(24); return o != 0 ? (RenderInfo?)(new RenderInfo()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int RenderDataLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static void StartModel(FlatBufferBuilder builder) { builder.StartObject(11); }
        public static void AddVersion(FlatBufferBuilder builder, uint Version) { builder.AddUint(0, Version, 0); }
        public static void AddBounding(FlatBufferBuilder builder, Offset<BoundingBox> BoundingOffset) { builder.AddStruct(1, BoundingOffset.Value, 0); }
        public static void AddTextureNames(FlatBufferBuilder builder, VectorOffset TextureNamesOffset) { builder.AddOffset(2, TextureNamesOffset.Value, 0); }
        public static VectorOffset CreateTextureNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateTextureNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartTextureNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddShaderNames(FlatBufferBuilder builder, VectorOffset ShaderNamesOffset) { builder.AddOffset(3, ShaderNamesOffset.Value, 0); }
        public static VectorOffset CreateShaderNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateShaderNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartShaderNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddUnknown(FlatBufferBuilder builder, VectorOffset UnknownOffset) { builder.AddOffset(4, UnknownOffset.Value, 0); }
        public static VectorOffset CreateUnknownVector(FlatBufferBuilder builder, Offset<UnknownEmpty>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateUnknownVectorBlock(FlatBufferBuilder builder, Offset<UnknownEmpty>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartUnknownVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMaterialNames(FlatBufferBuilder builder, VectorOffset MaterialNamesOffset) { builder.AddOffset(5, MaterialNamesOffset.Value, 0); }
        public static VectorOffset CreateMaterialNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateMaterialNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartMaterialNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMaterials(FlatBufferBuilder builder, VectorOffset MaterialsOffset) { builder.AddOffset(6, MaterialsOffset.Value, 0); }
        public static VectorOffset CreateMaterialsVector(FlatBufferBuilder builder, Offset<Material>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateMaterialsVectorBlock(FlatBufferBuilder builder, Offset<Material>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartMaterialsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddGroups(FlatBufferBuilder builder, VectorOffset GroupsOffset) { builder.AddOffset(7, GroupsOffset.Value, 0); }
        public static VectorOffset CreateGroupsVector(FlatBufferBuilder builder, Offset<Group>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateGroupsVectorBlock(FlatBufferBuilder builder, Offset<Group>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartGroupsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddMeshes(FlatBufferBuilder builder, VectorOffset MeshesOffset) { builder.AddOffset(8, MeshesOffset.Value, 0); }
        public static VectorOffset CreateMeshesVector(FlatBufferBuilder builder, Offset<Mesh>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateMeshesVectorBlock(FlatBufferBuilder builder, Offset<Mesh>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartMeshesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddBones(FlatBufferBuilder builder, VectorOffset BonesOffset) { builder.AddOffset(9, BonesOffset.Value, 0); }
        public static VectorOffset CreateBonesVector(FlatBufferBuilder builder, Offset<Bone>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateBonesVectorBlock(FlatBufferBuilder builder, Offset<Bone>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartBonesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddRenderData(FlatBufferBuilder builder, VectorOffset RenderDataOffset) { builder.AddOffset(10, RenderDataOffset.Value, 0); }
        public static VectorOffset CreateRenderDataVector(FlatBufferBuilder builder, Offset<RenderInfo>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateRenderDataVectorBlock(FlatBufferBuilder builder, Offset<RenderInfo>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartRenderDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<Model> EndModel(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<Model>(o);
        }
        public static void FinishModelBuffer(FlatBufferBuilder builder, Offset<Model> offset) { builder.Finish(offset.Value); }
        public static void FinishSizePrefixedModelBuffer(FlatBufferBuilder builder, Offset<Model> offset) { builder.FinishSizePrefixed(offset.Value); }
    };

    public struct UnknownEmpty : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static UnknownEmpty GetRootAsUnknownEmpty(ByteBuffer _bb) { return GetRootAsUnknownEmpty(_bb, new UnknownEmpty()); }
        public static UnknownEmpty GetRootAsUnknownEmpty(ByteBuffer _bb, UnknownEmpty obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public UnknownEmpty __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint Unk { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

        public static Offset<UnknownEmpty> CreateUnknownEmpty(FlatBufferBuilder builder,
            uint unk = 0)
        {
            builder.StartObject(1);
            UnknownEmpty.AddUnk(builder, unk);
            return UnknownEmpty.EndUnknownEmpty(builder);
        }

        public static void StartUnknownEmpty(FlatBufferBuilder builder) { builder.StartObject(1); }
        public static void AddUnk(FlatBufferBuilder builder, uint unk) { builder.AddUint(0, unk, 0); }
        public static Offset<UnknownEmpty> EndUnknownEmpty(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<UnknownEmpty>(o);
        }
    };

    public struct Material : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static Material GetRootAsMaterial(ByteBuffer _bb) { return GetRootAsMaterial(_bb, new Material()); }
        public static Material GetRootAsMaterial(ByteBuffer _bb, Material obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Material __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public string ShaderGroup { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetShaderGroupBytes() { return __p.__vector_as_span(6); }
#else
        public ArraySegment<byte>? GetShaderGroupBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public byte[] GetShaderGroupArray() { return __p.__vector_as_array<byte>(6); }
        public int RenderLayer { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public sbyte Unknown1 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public sbyte Unknown2 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public int Parameter1 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public int Parameter2 { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public int Parameter3 { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public int Parameter4 { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public int Parameter5 { get { int o = __p.__offset(22); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public int Parameter6 { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public TextureMap? Textures(int j) { int o = __p.__offset(26); return o != 0 ? (TextureMap?)(new TextureMap()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int TexturesLength { get { int o = __p.__offset(26); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MatSwitch? Switches(int j) { int o = __p.__offset(28); return o != 0 ? (MatSwitch?)(new MatSwitch()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int SwitchesLength { get { int o = __p.__offset(28); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MatFloat? Values(int j) { int o = __p.__offset(30); return o != 0 ? (MatFloat?)(new MatFloat()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ValuesLength { get { int o = __p.__offset(30); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MatColor? Colors(int j) { int o = __p.__offset(32); return o != 0 ? (MatColor?)(new MatColor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ColorsLength { get { int o = __p.__offset(32); return o != 0 ? __p.__vector_len(o) : 0; } }
        public sbyte Unknown3 { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public sbyte Unknown4 { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public sbyte Unknown5 { get { int o = __p.__offset(38); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public sbyte Unknown6 { get { int o = __p.__offset(40); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public sbyte Unknown7 { get { int o = __p.__offset(42); return o != 0 ? __p.bb.GetSbyte(o + __p.bb_pos) : (sbyte)0; } }
        public MaterialCommon? Common { get { int o = __p.__offset(44); return o != 0 ? (MaterialCommon?)(new MaterialCommon()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<Material> CreateMaterial(FlatBufferBuilder builder,
            StringOffset NameOffset = default(StringOffset),
            StringOffset ShaderGroupOffset = default(StringOffset),
            int RenderLayer = 0,
            sbyte Unknown1 = 0,
            sbyte Unknown2 = 0,
            int Parameter1 = 0,
            int Parameter2 = 0,
            int Parameter3 = 0,
            int Parameter4 = 0,
            int Parameter5 = 0,
            int Parameter6 = 0,
            VectorOffset TexturesOffset = default(VectorOffset),
            VectorOffset SwitchesOffset = default(VectorOffset),
            VectorOffset ValuesOffset = default(VectorOffset),
            VectorOffset ColorsOffset = default(VectorOffset),
            sbyte Unknown3 = 0,
            sbyte Unknown4 = 0,
            sbyte Unknown5 = 0,
            sbyte Unknown6 = 0,
            sbyte Unknown7 = 0,
            Offset<MaterialCommon> CommonOffset = default(Offset<MaterialCommon>))
        {
            builder.StartObject(21);
            Material.AddCommon(builder, CommonOffset);
            Material.AddColors(builder, ColorsOffset);
            Material.AddValues(builder, ValuesOffset);
            Material.AddSwitches(builder, SwitchesOffset);
            Material.AddTextures(builder, TexturesOffset);
            Material.AddParameter6(builder, Parameter6);
            Material.AddParameter5(builder, Parameter5);
            Material.AddParameter4(builder, Parameter4);
            Material.AddParameter3(builder, Parameter3);
            Material.AddParameter2(builder, Parameter2);
            Material.AddParameter1(builder, Parameter1);
            Material.AddRenderLayer(builder, RenderLayer);
            Material.AddShaderGroup(builder, ShaderGroupOffset);
            Material.AddName(builder, NameOffset);
            Material.AddUnknown7(builder, Unknown7);
            Material.AddUnknown6(builder, Unknown6);
            Material.AddUnknown5(builder, Unknown5);
            Material.AddUnknown4(builder, Unknown4);
            Material.AddUnknown3(builder, Unknown3);
            Material.AddUnknown2(builder, Unknown2);
            Material.AddUnknown1(builder, Unknown1);
            return Material.EndMaterial(builder);
        }

        public static void StartMaterial(FlatBufferBuilder builder) { builder.StartObject(21); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddShaderGroup(FlatBufferBuilder builder, StringOffset ShaderGroupOffset) { builder.AddOffset(1, ShaderGroupOffset.Value, 0); }
        public static void AddRenderLayer(FlatBufferBuilder builder, int RenderLayer) { builder.AddInt(2, RenderLayer, 0); }
        public static void AddUnknown1(FlatBufferBuilder builder, sbyte Unknown1) { builder.AddSbyte(3, Unknown1, 0); }
        public static void AddUnknown2(FlatBufferBuilder builder, sbyte Unknown2) { builder.AddSbyte(4, Unknown2, 0); }
        public static void AddParameter1(FlatBufferBuilder builder, int Parameter1) { builder.AddInt(5, Parameter1, 0); }
        public static void AddParameter2(FlatBufferBuilder builder, int Parameter2) { builder.AddInt(6, Parameter2, 0); }
        public static void AddParameter3(FlatBufferBuilder builder, int Parameter3) { builder.AddInt(7, Parameter3, 0); }
        public static void AddParameter4(FlatBufferBuilder builder, int Parameter4) { builder.AddInt(8, Parameter4, 0); }
        public static void AddParameter5(FlatBufferBuilder builder, int Parameter5) { builder.AddInt(9, Parameter5, 0); }
        public static void AddParameter6(FlatBufferBuilder builder, int Parameter6) { builder.AddInt(10, Parameter6, 0); }
        public static void AddTextures(FlatBufferBuilder builder, VectorOffset TexturesOffset) { builder.AddOffset(11, TexturesOffset.Value, 0); }
        public static VectorOffset CreateTexturesVector(FlatBufferBuilder builder, Offset<TextureMap>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateTexturesVectorBlock(FlatBufferBuilder builder, Offset<TextureMap>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartTexturesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddSwitches(FlatBufferBuilder builder, VectorOffset SwitchesOffset) { builder.AddOffset(12, SwitchesOffset.Value, 0); }
        public static VectorOffset CreateSwitchesVector(FlatBufferBuilder builder, Offset<MatSwitch>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateSwitchesVectorBlock(FlatBufferBuilder builder, Offset<MatSwitch>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartSwitchesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddValues(FlatBufferBuilder builder, VectorOffset ValuesOffset) { builder.AddOffset(13, ValuesOffset.Value, 0); }
        public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<MatFloat>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<MatFloat>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddColors(FlatBufferBuilder builder, VectorOffset ColorsOffset) { builder.AddOffset(14, ColorsOffset.Value, 0); }
        public static VectorOffset CreateColorsVector(FlatBufferBuilder builder, Offset<MatColor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateColorsVectorBlock(FlatBufferBuilder builder, Offset<MatColor>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartColorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddUnknown3(FlatBufferBuilder builder, sbyte Unknown3) { builder.AddSbyte(15, Unknown3, 0); }
        public static void AddUnknown4(FlatBufferBuilder builder, sbyte Unknown4) { builder.AddSbyte(16, Unknown4, 0); }
        public static void AddUnknown5(FlatBufferBuilder builder, sbyte Unknown5) { builder.AddSbyte(17, Unknown5, 0); }
        public static void AddUnknown6(FlatBufferBuilder builder, sbyte Unknown6) { builder.AddSbyte(18, Unknown6, 0); }
        public static void AddUnknown7(FlatBufferBuilder builder, sbyte Unknown7) { builder.AddSbyte(19, Unknown7, 0); }
        public static void AddCommon(FlatBufferBuilder builder, Offset<MaterialCommon> CommonOffset) { builder.AddOffset(20, CommonOffset.Value, 0); }
        public static Offset<Material> EndMaterial(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<Material>(o);
        }
    };

    public struct MaterialCommon : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MaterialCommon GetRootAsMaterialCommon(ByteBuffer _bb) { return GetRootAsMaterialCommon(_bb, new MaterialCommon()); }
        public static MaterialCommon GetRootAsMaterialCommon(ByteBuffer _bb, MaterialCommon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MaterialCommon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public MatSwitch? Switches(int j) { int o = __p.__offset(4); return o != 0 ? (MatSwitch?)(new MatSwitch()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int SwitchesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MatInt? Values(int j) { int o = __p.__offset(6); return o != 0 ? (MatInt?)(new MatInt()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ValuesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MatColor? Colors(int j) { int o = __p.__offset(8); return o != 0 ? (MatColor?)(new MatColor()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int ColorsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

        public static Offset<MaterialCommon> CreateMaterialCommon(FlatBufferBuilder builder,
            VectorOffset SwitchesOffset = default(VectorOffset),
            VectorOffset ValuesOffset = default(VectorOffset),
            VectorOffset ColorsOffset = default(VectorOffset))
        {
            builder.StartObject(3);
            MaterialCommon.AddColors(builder, ColorsOffset);
            MaterialCommon.AddValues(builder, ValuesOffset);
            MaterialCommon.AddSwitches(builder, SwitchesOffset);
            return MaterialCommon.EndMaterialCommon(builder);
        }

        public static void StartMaterialCommon(FlatBufferBuilder builder) { builder.StartObject(3); }
        public static void AddSwitches(FlatBufferBuilder builder, VectorOffset SwitchesOffset) { builder.AddOffset(0, SwitchesOffset.Value, 0); }
        public static VectorOffset CreateSwitchesVector(FlatBufferBuilder builder, Offset<MatSwitch>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateSwitchesVectorBlock(FlatBufferBuilder builder, Offset<MatSwitch>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartSwitchesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddValues(FlatBufferBuilder builder, VectorOffset ValuesOffset) { builder.AddOffset(1, ValuesOffset.Value, 0); }
        public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<MatInt>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<MatInt>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddColors(FlatBufferBuilder builder, VectorOffset ColorsOffset) { builder.AddOffset(2, ColorsOffset.Value, 0); }
        public static VectorOffset CreateColorsVector(FlatBufferBuilder builder, Offset<MatColor>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateColorsVectorBlock(FlatBufferBuilder builder, Offset<MatColor>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartColorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static Offset<MaterialCommon> EndMaterialCommon(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MaterialCommon>(o);
        }
    };

    public struct MatSwitch : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MatSwitch GetRootAsMatSwitch(ByteBuffer _bb) { return GetRootAsMatSwitch(_bb, new MatSwitch()); }
        public static MatSwitch GetRootAsMatSwitch(ByteBuffer _bb, MatSwitch obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MatSwitch __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public bool Value { get { int o = __p.__offset(6); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }

        public static Offset<MatSwitch> CreateMatSwitch(FlatBufferBuilder builder,
            StringOffset NameOffset = default(StringOffset),
            bool Value = false)
        {
            builder.StartObject(2);
            MatSwitch.AddName(builder, NameOffset);
            MatSwitch.AddValue(builder, Value);
            return MatSwitch.EndMatSwitch(builder);
        }

        public static void StartMatSwitch(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, bool Value) { builder.AddBool(1, Value, false); }
        public static Offset<MatSwitch> EndMatSwitch(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MatSwitch>(o);
        }
    };

    public struct MatColor : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MatColor GetRootAsMatColor(ByteBuffer _bb) { return GetRootAsMatColor(_bb, new MatColor()); }
        public static MatColor GetRootAsMatColor(ByteBuffer _bb, MatColor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MatColor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public ColorRGB32? Color { get { int o = __p.__offset(6); return o != 0 ? (ColorRGB32?)(new ColorRGB32()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static void StartMatColor(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddColor(FlatBufferBuilder builder, Offset<ColorRGB32> ColorOffset) { builder.AddStruct(1, ColorOffset.Value, 0); }
        public static Offset<MatColor> EndMatColor(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MatColor>(o);
        }
    };

    public struct MatInt : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MatInt GetRootAsMatInt(ByteBuffer _bb) { return GetRootAsMatInt(_bb, new MatInt()); }
        public static MatInt GetRootAsMatInt(ByteBuffer _bb, MatInt obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MatInt __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public int Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

        public static Offset<MatInt> CreateMatInt(FlatBufferBuilder builder,
            StringOffset NameOffset = default(StringOffset),
            int Value = 0)
        {
            builder.StartObject(2);
            MatInt.AddValue(builder, Value);
            MatInt.AddName(builder, NameOffset);
            return MatInt.EndMatInt(builder);
        }

        public static void StartMatInt(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, int Value) { builder.AddInt(1, Value, 0); }
        public static Offset<MatInt> EndMatInt(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MatInt>(o);
        }
    };

    public struct MatFloat : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MatFloat GetRootAsMatFloat(ByteBuffer _bb) { return GetRootAsMatFloat(_bb, new MatFloat()); }
        public static MatFloat GetRootAsMatFloat(ByteBuffer _bb, MatFloat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MatFloat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public float Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

        public static Offset<MatFloat> CreateMatFloat(FlatBufferBuilder builder,
            StringOffset NameOffset = default(StringOffset),
            float Value = 0.0f)
        {
            builder.StartObject(2);
            MatFloat.AddValue(builder, Value);
            MatFloat.AddName(builder, NameOffset);
            return MatFloat.EndMatFloat(builder);
        }

        public static void StartMatFloat(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddValue(FlatBufferBuilder builder, float Value) { builder.AddFloat(1, Value, 0.0f); }
        public static Offset<MatFloat> EndMatFloat(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MatFloat>(o);
        }
    };

    public struct TextureMap : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static TextureMap GetRootAsTextureMap(ByteBuffer _bb) { return GetRootAsTextureMap(_bb, new TextureMap()); }
        public static TextureMap GetRootAsTextureMap(ByteBuffer _bb, TextureMap obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public TextureMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public int Index { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public TextureMapping? Mapping { get { int o = __p.__offset(8); return o != 0 ? (TextureMapping?)(new TextureMapping()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<TextureMap> CreateTextureMap(FlatBufferBuilder builder,
            StringOffset NameOffset = default(StringOffset),
            int Index = 0,
            Offset<TextureMapping> MappingOffset = default(Offset<TextureMapping>))
        {
            builder.StartObject(3);
            TextureMap.AddMapping(builder, MappingOffset);
            TextureMap.AddIndex(builder, Index);
            TextureMap.AddName(builder, NameOffset);
            return TextureMap.EndTextureMap(builder);
        }

        public static void StartTextureMap(FlatBufferBuilder builder) { builder.StartObject(3); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddIndex(FlatBufferBuilder builder, int Index) { builder.AddInt(1, Index, 0); }
        public static void AddMapping(FlatBufferBuilder builder, Offset<TextureMapping> MappingOffset) { builder.AddOffset(2, MappingOffset.Value, 0); }
        public static Offset<TextureMap> EndTextureMap(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<TextureMap>(o);
        }
    };

    public struct TextureMapping : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static TextureMapping GetRootAsTextureMapping(ByteBuffer _bb) { return GetRootAsTextureMapping(_bb, new TextureMapping()); }
        public static TextureMapping GetRootAsTextureMapping(ByteBuffer _bb, TextureMapping obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public TextureMapping __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint Type { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint Scale { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint Translation { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint Rotation { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint WrapS { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint WrapT { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint MagFilter { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint MinFilter { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public float MinLOD { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

        public static Offset<TextureMapping> CreateTextureMapping(FlatBufferBuilder builder,
            uint Type = 0,
            uint Scale = 0,
            uint Translation = 0,
            uint Rotation = 0,
            uint WrapS = 0,
            uint WrapT = 0,
            uint magFilter = 0,
            uint minFilter = 0,
            float minLOD = 0.0f)
        {
            builder.StartObject(9);
            TextureMapping.AddMinLOD(builder, minLOD);
            TextureMapping.AddMinFilter(builder, minFilter);
            TextureMapping.AddMagFilter(builder, magFilter);
            TextureMapping.AddWrapT(builder, WrapT);
            TextureMapping.AddWrapS(builder, WrapS);
            TextureMapping.AddRotation(builder, Rotation);
            TextureMapping.AddTranslation(builder, Translation);
            TextureMapping.AddScale(builder, Scale);
            TextureMapping.AddType(builder, Type);
            return TextureMapping.EndTextureMapping(builder);
        }

        public static void StartTextureMapping(FlatBufferBuilder builder) { builder.StartObject(9); }
        public static void AddType(FlatBufferBuilder builder, uint Type) { builder.AddUint(0, Type, 0); }
        public static void AddScale(FlatBufferBuilder builder, uint Scale) { builder.AddUint(1, Scale, 0); }
        public static void AddTranslation(FlatBufferBuilder builder, uint Translation) { builder.AddUint(2, Translation, 0); }
        public static void AddRotation(FlatBufferBuilder builder, uint Rotation) { builder.AddUint(3, Rotation, 0); }
        public static void AddWrapS(FlatBufferBuilder builder, uint WrapS) { builder.AddUint(4, WrapS, 0); }
        public static void AddWrapT(FlatBufferBuilder builder, uint WrapT) { builder.AddUint(5, WrapT, 0); }
        public static void AddMagFilter(FlatBufferBuilder builder, uint magFilter) { builder.AddUint(6, magFilter, 0); }
        public static void AddMinFilter(FlatBufferBuilder builder, uint minFilter) { builder.AddUint(7, minFilter, 0); }
        public static void AddMinLOD(FlatBufferBuilder builder, float minLOD) { builder.AddFloat(8, minLOD, 0.0f); }
        public static Offset<TextureMapping> EndTextureMapping(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<TextureMapping>(o);
        }
    };

    public struct Group : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static Group GetRootAsGroup(ByteBuffer _bb) { return GetRootAsGroup(_bb, new Group()); }
        public static Group GetRootAsGroup(ByteBuffer _bb, Group obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Group __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint BoneID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint MeshID { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public BoundingBox? Bounding { get { int o = __p.__offset(8); return o != 0 ? (BoundingBox?)(new BoundingBox()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public uint Layer { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

        public static void StartGroup(FlatBufferBuilder builder) { builder.StartObject(4); }
        public static void AddBoneID(FlatBufferBuilder builder, uint boneID) { builder.AddUint(0, boneID, 0); }
        public static void AddMeshID(FlatBufferBuilder builder, uint meshID) { builder.AddUint(1, meshID, 0); }
        public static void AddBounding(FlatBufferBuilder builder, Offset<BoundingBox> BoundingOffset) { builder.AddStruct(2, BoundingOffset.Value, 0); }
        public static void AddLayer(FlatBufferBuilder builder, uint layer) { builder.AddUint(3, layer, 0); }
        public static Offset<Group> EndGroup(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<Group>(o);
        }
    };

    public struct Mesh : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static Mesh GetRootAsMesh(ByteBuffer _bb) { return GetRootAsMesh(_bb, new Mesh()); }
        public static Mesh GetRootAsMesh(ByteBuffer _bb, Mesh obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Mesh __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public MeshPolygon? Polygons(int j) { int o = __p.__offset(4); return o != 0 ? (MeshPolygon?)(new MeshPolygon()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int PolygonsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
        public MeshAlignment? Alignments(int j) { int o = __p.__offset(6); return o != 0 ? (MeshAlignment?)(new MeshAlignment()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
        public int AlignmentsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
        public byte Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
        public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span(8); }
#else
        public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
        public byte[] GetDataArray() { return __p.__vector_as_array<byte>(8); }

        public static Offset<Mesh> CreateMesh(FlatBufferBuilder builder,
            VectorOffset PolygonsOffset = default(VectorOffset),
            VectorOffset AlignmentsOffset = default(VectorOffset),
            VectorOffset DataOffset = default(VectorOffset))
        {
            builder.StartObject(3);
            Mesh.AddData(builder, DataOffset);
            Mesh.AddAlignments(builder, AlignmentsOffset);
            Mesh.AddPolygons(builder, PolygonsOffset);
            return Mesh.EndMesh(builder);
        }

        public static void StartMesh(FlatBufferBuilder builder) { builder.StartObject(3); }
        public static void AddPolygons(FlatBufferBuilder builder, VectorOffset PolygonsOffset) { builder.AddOffset(0, PolygonsOffset.Value, 0); }
        public static VectorOffset CreatePolygonsVector(FlatBufferBuilder builder, Offset<MeshPolygon>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreatePolygonsVectorBlock(FlatBufferBuilder builder, Offset<MeshPolygon>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartPolygonsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddAlignments(FlatBufferBuilder builder, VectorOffset AlignmentsOffset) { builder.AddOffset(1, AlignmentsOffset.Value, 0); }
        public static VectorOffset CreateAlignmentsVector(FlatBufferBuilder builder, Offset<MeshAlignment>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
        public static VectorOffset CreateAlignmentsVectorBlock(FlatBufferBuilder builder, Offset<MeshAlignment>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
        public static void StartAlignmentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
        public static void AddData(FlatBufferBuilder builder, VectorOffset DataOffset) { builder.AddOffset(2, DataOffset.Value, 0); }
        public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
        public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
        public static Offset<Mesh> EndMesh(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<Mesh>(o);
        }
    };

    public struct MeshPolygon : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MeshPolygon GetRootAsMeshPolygon(ByteBuffer _bb) { return GetRootAsMeshPolygon(_bb, new MeshPolygon()); }
        public static MeshPolygon GetRootAsMeshPolygon(ByteBuffer _bb, MeshPolygon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MeshPolygon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint MaterialID { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public ushort Data(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(__p.__vector(o) + j * 2) : (ushort)0; }
        public int DataLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span(6); }
#else
        public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(6); }
#endif
        public ushort[] GetDataArray() { return __p.__vector_as_array<ushort>(6); }

        public static Offset<MeshPolygon> CreateMeshPolygon(FlatBufferBuilder builder,
            uint materialID = 0,
            VectorOffset dataOffset = default(VectorOffset))
        {
            builder.StartObject(2);
            MeshPolygon.AddData(builder, dataOffset);
            MeshPolygon.AddMaterialID(builder, materialID);
            return MeshPolygon.EndMeshPolygon(builder);
        }

        public static void StartMeshPolygon(FlatBufferBuilder builder) { builder.StartObject(2); }
        public static void AddMaterialID(FlatBufferBuilder builder, uint materialID) { builder.AddUint(0, materialID, 0); }
        public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(1, dataOffset.Value, 0); }
        public static VectorOffset CreateDataVector(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddUshort(data[i]); return builder.EndVector(); }
        public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
        public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
        public static Offset<MeshPolygon> EndMeshPolygon(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MeshPolygon>(o);
        }
    };

    public struct MeshAlignment : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static MeshAlignment GetRootAsMeshAlignment(ByteBuffer _bb) { return GetRootAsMeshAlignment(_bb, new MeshAlignment()); }
        public static MeshAlignment GetRootAsMeshAlignment(ByteBuffer _bb, MeshAlignment obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public MeshAlignment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public VertexType TypeID { get { int o = __p.__offset(4); return o != 0 ? (VertexType)__p.bb.GetUint(o + __p.bb_pos) : VertexType.Position; } }
        public BufferFormat FormatID { get { int o = __p.__offset(6); return o != 0 ? (BufferFormat)__p.bb.GetUint(o + __p.bb_pos) : BufferFormat.Float; } }
        public uint ElementCount { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

        public static Offset<MeshAlignment> CreateMeshAlignment(FlatBufferBuilder builder,
            VertexType TypeID = VertexType.Position,
            BufferFormat FormatID = BufferFormat.Float,
            uint ElementCount = 0)
        {
            builder.StartObject(3);
            MeshAlignment.AddElementCount(builder, ElementCount);
            MeshAlignment.AddFormatID(builder, FormatID);
            MeshAlignment.AddTypeID(builder, TypeID);
            return MeshAlignment.EndMeshAlignment(builder);
        }

        public static void StartMeshAlignment(FlatBufferBuilder builder) { builder.StartObject(3); }
        public static void AddTypeID(FlatBufferBuilder builder, VertexType TypeID) { builder.AddUint(0, (uint)TypeID, 0); }
        public static void AddFormatID(FlatBufferBuilder builder, BufferFormat FormatID) { builder.AddUint(1, (uint)FormatID, 0); }
        public static void AddElementCount(FlatBufferBuilder builder, uint ElementCount) { builder.AddUint(2, ElementCount, 0); }
        public static Offset<MeshAlignment> EndMeshAlignment(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<MeshAlignment>(o);
        }
    };

    public struct Bone : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static Bone GetRootAsBone(ByteBuffer _bb) { return GetRootAsBone(_bb, new Bone()); }
        public static Bone GetRootAsBone(ByteBuffer _bb, Bone obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Bone __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span(4); }
#else
        public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
        public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
        public BoneType Type { get { int o = __p.__offset(6); return o != 0 ? (BoneType)__p.bb.GetUint(o + __p.bb_pos) : BoneType.NoSkinning; } }
        public int Parent { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
        public uint Zero { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public bool Visible { get { int o = __p.__offset(12); return o != 0 ? 0 != __p.bb.Get(o + __p.bb_pos) : (bool)false; } }
        public Vector3? Scale { get { int o = __p.__offset(14); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public Vector3? Rotation { get { int o = __p.__offset(16); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public Vector3? Translation { get { int o = __p.__offset(18); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public Vector3? RadiusStart { get { int o = __p.__offset(20); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public Vector3? RadiusEnd { get { int o = __p.__offset(22); return o != 0 ? (Vector3?)(new Vector3()).__assign(o + __p.bb_pos, __p.bb) : null; } }
        public UnknownData? SkinCheck { get { int o = __p.__offset(24); return o != 0 ? (UnknownData?)(new UnknownData()).__assign(o + __p.bb_pos, __p.bb) : null; } }

        public static void StartBone(FlatBufferBuilder builder) { builder.StartObject(11); }
        public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(0, NameOffset.Value, 0); }
        public static void AddType(FlatBufferBuilder builder, BoneType Type) { builder.AddUint(1, (uint)Type, 0); }
        public static void AddParent(FlatBufferBuilder builder, int Parent) { builder.AddInt(2, Parent, 0); }
        public static void AddZero(FlatBufferBuilder builder, uint Zero) { builder.AddUint(3, Zero, 0); }
        public static void AddVisible(FlatBufferBuilder builder, bool Visible) { builder.AddBool(4, Visible, false); }
        public static void AddScale(FlatBufferBuilder builder, Offset<Vector3> ScaleOffset) { builder.AddStruct(5, ScaleOffset.Value, 0); }
        public static void AddRotation(FlatBufferBuilder builder, Offset<Vector3> RotationOffset) { builder.AddStruct(6, RotationOffset.Value, 0); }
        public static void AddTranslation(FlatBufferBuilder builder, Offset<Vector3> TranslationOffset) { builder.AddStruct(7, TranslationOffset.Value, 0); }
        public static void AddRadiusStart(FlatBufferBuilder builder, Offset<Vector3> RadiusStartOffset) { builder.AddStruct(8, RadiusStartOffset.Value, 0); }
        public static void AddRadiusEnd(FlatBufferBuilder builder, Offset<Vector3> RadiusEndOffset) { builder.AddStruct(9, RadiusEndOffset.Value, 0); }
        public static void AddSkinCheck(FlatBufferBuilder builder, Offset<UnknownData> SkinCheckOffset) { builder.AddStruct(10, SkinCheckOffset.Value, 0); }
        public static Offset<Bone> EndBone(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<Bone>(o);
        }
    };

    public struct UnknownData : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public UnknownData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public sbyte NoSkin { get { return __p.bb.GetSbyte(__p.bb_pos + 0); } }

        public static Offset<UnknownData> CreateUnknownData(FlatBufferBuilder builder, sbyte NoSkin)
        {
            builder.Prep(1, 1);
            builder.PutSbyte(NoSkin);
            return new Offset<UnknownData>(builder.Offset);
        }
    };

    public struct RenderInfo : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static RenderInfo GetRootAsRenderInfo(ByteBuffer _bb) { return GetRootAsRenderInfo(_bb, new RenderInfo()); }
        public static RenderInfo GetRootAsRenderInfo(ByteBuffer _bb, RenderInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public RenderInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint Unknown1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public uint Unknown2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
        public RenderUnknown? Unknown3 { get { int o = __p.__offset(8); return o != 0 ? (RenderUnknown?)(new RenderUnknown()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
        public RenderUnknown2? Unknown4 { get { int o = __p.__offset(10); return o != 0 ? (RenderUnknown2?)(new RenderUnknown2()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

        public static Offset<RenderInfo> CreateRenderInfo(FlatBufferBuilder builder,
            uint Unknown1 = 0,
            uint Unknown2 = 0,
            Offset<RenderUnknown> Unknown3Offset = default(Offset<RenderUnknown>),
            Offset<RenderUnknown2> Unknown4Offset = default(Offset<RenderUnknown2>))
        {
            builder.StartObject(4);
            RenderInfo.AddUnknown4(builder, Unknown4Offset);
            RenderInfo.AddUnknown3(builder, Unknown3Offset);
            RenderInfo.AddUnknown2(builder, Unknown2);
            RenderInfo.AddUnknown1(builder, Unknown1);
            return RenderInfo.EndRenderInfo(builder);
        }

        public static void StartRenderInfo(FlatBufferBuilder builder) { builder.StartObject(4); }
        public static void AddUnknown1(FlatBufferBuilder builder, uint Unknown1) { builder.AddUint(0, Unknown1, 0); }
        public static void AddUnknown2(FlatBufferBuilder builder, uint Unknown2) { builder.AddUint(1, Unknown2, 0); }
        public static void AddUnknown3(FlatBufferBuilder builder, Offset<RenderUnknown> Unknown3Offset) { builder.AddOffset(2, Unknown3Offset.Value, 0); }
        public static void AddUnknown4(FlatBufferBuilder builder, Offset<RenderUnknown2> Unknown4Offset) { builder.AddOffset(3, Unknown4Offset.Value, 0); }
        public static Offset<RenderInfo> EndRenderInfo(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<RenderInfo>(o);
        }
    };

    public struct RenderUnknown : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static RenderUnknown GetRootAsRenderUnknown(ByteBuffer _bb) { return GetRootAsRenderUnknown(_bb, new RenderUnknown()); }
        public static RenderUnknown GetRootAsRenderUnknown(ByteBuffer _bb, RenderUnknown obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public RenderUnknown __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public uint Unknown { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

        public static Offset<RenderUnknown> CreateRenderUnknown(FlatBufferBuilder builder,
            uint Unknown = 0)
        {
            builder.StartObject(1);
            RenderUnknown.AddUnknown(builder, Unknown);
            return RenderUnknown.EndRenderUnknown(builder);
        }

        public static void StartRenderUnknown(FlatBufferBuilder builder) { builder.StartObject(1); }
        public static void AddUnknown(FlatBufferBuilder builder, uint Unknown) { builder.AddUint(0, Unknown, 0); }
        public static Offset<RenderUnknown> EndRenderUnknown(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<RenderUnknown>(o);
        }
    };

    public struct RenderUnknown2 : IFlatbufferObject
    {
        private Table __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public static RenderUnknown2 GetRootAsRenderUnknown2(ByteBuffer _bb) { return GetRootAsRenderUnknown2(_bb, new RenderUnknown2()); }
        public static RenderUnknown2 GetRootAsRenderUnknown2(ByteBuffer _bb, RenderUnknown2 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public RenderUnknown2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float Unknown1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public float Unknown2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public float Unknown3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public float Unknown4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public float Unknown5 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
        public float Unknown6 { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

        public static Offset<RenderUnknown2> CreateRenderUnknown2(FlatBufferBuilder builder,
            float Unknown1 = 0.0f,
            float Unknown2 = 0.0f,
            float Unknown3 = 0.0f,
            float Unknown4 = 0.0f,
            float Unknown5 = 0.0f,
            float Unknown6 = 0.0f)
        {
            builder.StartObject(6);
            RenderUnknown2.AddUnknown6(builder, Unknown6);
            RenderUnknown2.AddUnknown5(builder, Unknown5);
            RenderUnknown2.AddUnknown4(builder, Unknown4);
            RenderUnknown2.AddUnknown3(builder, Unknown3);
            RenderUnknown2.AddUnknown2(builder, Unknown2);
            RenderUnknown2.AddUnknown1(builder, Unknown1);
            return RenderUnknown2.EndRenderUnknown2(builder);
        }

        public static void StartRenderUnknown2(FlatBufferBuilder builder) { builder.StartObject(6); }
        public static void AddUnknown1(FlatBufferBuilder builder, float Unknown1) { builder.AddFloat(0, Unknown1, 0.0f); }
        public static void AddUnknown2(FlatBufferBuilder builder, float Unknown2) { builder.AddFloat(1, Unknown2, 0.0f); }
        public static void AddUnknown3(FlatBufferBuilder builder, float Unknown3) { builder.AddFloat(2, Unknown3, 0.0f); }
        public static void AddUnknown4(FlatBufferBuilder builder, float Unknown4) { builder.AddFloat(3, Unknown4, 0.0f); }
        public static void AddUnknown5(FlatBufferBuilder builder, float Unknown5) { builder.AddFloat(4, Unknown5, 0.0f); }
        public static void AddUnknown6(FlatBufferBuilder builder, float Unknown6) { builder.AddFloat(5, Unknown6, 0.0f); }
        public static Offset<RenderUnknown2> EndRenderUnknown2(FlatBufferBuilder builder)
        {
            int o = builder.EndObject();
            return new Offset<RenderUnknown2>(o);
        }
    };

    public struct BoundingBox : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public BoundingBox __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float MinX { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public float MinY { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
        public float MinZ { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
        public float MaxX { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }
        public float MaxY { get { return __p.bb.GetFloat(__p.bb_pos + 16); } }
        public float MaxZ { get { return __p.bb.GetFloat(__p.bb_pos + 20); } }

        public static Offset<BoundingBox> CreateBoundingBox(FlatBufferBuilder builder, float MinX, float MinY, float MinZ, float MaxX, float MaxY, float MaxZ)
        {
            builder.Prep(4, 24);
            builder.PutFloat(MaxZ);
            builder.PutFloat(MaxY);
            builder.PutFloat(MaxX);
            builder.PutFloat(MinZ);
            builder.PutFloat(MinY);
            builder.PutFloat(MinX);
            return new Offset<BoundingBox>(builder.Offset);
        }
    };

    public struct Vector3 : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Vector3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
        public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

        public static Offset<Vector3> CreateVector3(FlatBufferBuilder builder, float X, float Y, float Z)
        {
            builder.Prep(4, 12);
            builder.PutFloat(Z);
            builder.PutFloat(Y);
            builder.PutFloat(X);
            return new Offset<Vector3>(builder.Offset);
        }
    };

    public struct ColorRGB32 : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public ColorRGB32 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float R { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public float G { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
        public float B { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }

        public static Offset<ColorRGB32> CreateColorRGB32(FlatBufferBuilder builder, float R, float G, float B)
        {
            builder.Prep(4, 12);
            builder.PutFloat(B);
            builder.PutFloat(G);
            builder.PutFloat(R);
            return new Offset<ColorRGB32>(builder.Offset);
        }
    };

    public struct Vector4 : IFlatbufferObject
    {
        private Struct __p;
        public ByteBuffer ByteBuffer { get { return __p.bb; } }
        public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
        public Vector4 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

        public float X { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
        public float Y { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
        public float Z { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
        public float W { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

        public static Offset<Vector4> CreateVector4(FlatBufferBuilder builder, float X, float Y, float Z, float W)
        {
            builder.Prep(4, 16);
            builder.PutFloat(W);
            builder.PutFloat(Z);
            builder.PutFloat(Y);
            builder.PutFloat(X);
            return new Offset<Vector4>(builder.Offset);
        }
    };


}
