//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddIcon {
            get {
                object obj = ResourceManager.GetObject("AddIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AlignmentPane {
            get {
                object obj = ResourceManager.GetObject("AlignmentPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ArrowIcon {
            get {
                object obj = ResourceManager.GetObject("ArrowIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowMinimize_ {
            get {
                object obj = ResourceManager.GetObject("arrowMinimize ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrowMinimize_1 {
            get {
                object obj = ResourceManager.GetObject("arrowMinimize 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Basic_Bake_st0 {
            get {
                object obj = ResourceManager.GetObject("Basic_Bake_st0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Basic_Bake_st1 {
            get {
                object obj = ResourceManager.GetObject("Basic_Bake_st1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Basic_Nrm {
            get {
                object obj = ResourceManager.GetObject("Basic_Nrm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Basic_NrmBC5 {
            get {
                object obj = ResourceManager.GetObject("Basic_NrmBC5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Black {
            get {
                object obj = ResourceManager.GetObject("Black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BoundryPane {
            get {
                object obj = ResourceManager.GetObject("BoundryPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GridBackground {
            get {
                object obj = ResourceManager.GetObject("GridBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] InjectTexErrored {
            get {
                object obj = ResourceManager.GetObject("InjectTexErrored", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LayoutAnimation {
            get {
                object obj = ResourceManager.GetObject("LayoutAnimation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1
        ///boo
        ///fan
        ///ice
        ///ivy
        ///lob
        ///net
        ///nub
        ///sky
        ///_vicenight/riotguard/thigh1
        ///_vicenight/riotguard/thigh2
        ///_vicenight/riotguard/thigh3
        ///GenGlow
        ///fx_divot_flash
        ///_craterfield/podsspec
        ///IDLE
        ///Idle
        ///Main
        ///_tutorialfield/wall_base
        ///Pass
        ///_tutorialfield/wall_mask
        ///_tutorialfield/wall_spec
        ///arg1
        ///arm1
        ///ball
        ///blue
        ///boot
        ///drum
        ///dump
        ///fins
        ///fire
        ///flag
        ///glow
        ///gold
        ///hull
        ///land
        ///leg1
        ///leg2
        ///leg3
        ///lid1
        ///lid2
        ///lid3
        ///mast
        ///palm
        ///pole
        ///pots
        ///rock
        ///roof
        ///rope
        ///sand
        ///star
        ///stop
        ///toad
        ///tree
        ///whip
        ///wood
        ///proxy object05/claw1
        ///proxy  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LM3_Hashes {
            get {
                return ResourceManager.GetString("LM3_Hashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MetroidDread {
            get {
                object obj = ResourceManager.GetObject("MetroidDread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MissingTexture {
            get {
                object obj = ResourceManager.GetObject("MissingTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NullPane {
            get {
                object obj = ResourceManager.GetObject("NullPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OrthoView {
            get {
                object obj = ResourceManager.GetObject("OrthoView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PicturePane {
            get {
                object obj = ResourceManager.GetObject("PicturePane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pc0002_00_fa0004_eye_close01.gfbanm
        ///pc0002_00_fi0001_wait01_loop.gfbanm
        ///bin/pokemon/pmXXXX_00/
        ///bin/pokemon/pmXXXX_00/tex/
        ///bin/pokemon/pmXXXX_00/anm/
        ///bin/pokemon/pmXXXX_00/mdl/
        ///bin/pokemon_data/
        ///bin/graphics/mask_texture/pattern_01/
        ///bin/app/pokecamp/cooking/common_model/anm/
        ///bin/app/pokecamp/cooking/common_model/mdl/
        ///bin/app/pokecamp/cooking/common_model/
        ///bin/chara/data/pc/p2/p1_base_app01/anm/
        ///pmXXXX_00.gfbpokecfg
        ///pmXXXX_00.gfbmdl
        ///pmXXXX_00_rare.gfbmdl
        ///pmXXXX_00_field01.gfbanmcfg
        ///pmXXXX_00_f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Pkmn {
            get {
                return ResourceManager.GetString("Pkmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuickAccess {
            get {
                object obj = ResourceManager.GetObject("QuickAccess", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RemoveIcon {
            get {
                object obj = ResourceManager.GetObject("RemoveIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScissorPane {
            get {
                object obj = ResourceManager.GetObject("ScissorPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextPane {
            get {
                object obj = ResourceManager.GetObject("TextPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextureError {
            get {
                object obj = ResourceManager.GetObject("TextureError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewportIcon {
            get {
                object obj = ResourceManager.GetObject("ViewportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ViewportIconDisable {
            get {
                object obj = ResourceManager.GetObject("ViewportIconDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] White {
            get {
                object obj = ResourceManager.GetObject("White", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowPane {
            get {
                object obj = ResourceManager.GetObject("WindowPane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XLink {
            get {
                object obj = ResourceManager.GetObject("XLink", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
